ALTER TABLE `user`
  ADD COLUMN `email` VARCHAR(100) NOT NULL  AFTER `password`,
  ADD COLUMN `suspend` TINYINT(1) NOT NULL DEFAULT 0  AFTER `salt`,
  ADD COLUMN `date_created` TIMESTAMP NOT NULL DEFAULT '0000-00-00' AFTER `suspend`,
  ADD COLUMN `date_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `date_created`,
  CHANGE COLUMN `username` `username` VARCHAR(100) NOT NULL,
  CHANGE COLUMN `password` `password` VARCHAR(40) NOT NULL,
  CHANGE COLUMN `salt` `salt` VARCHAR(255) NOT NULL,
  ADD UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  ADD UNIQUE INDEX `email_UNIQUE` (`email` ASC);
