<?php

/**
 * This is the model base class for the table "tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tag".
 *
 * Columns in table "tag" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $tag
 * @property string $weight
 *
 */
abstract class BaseTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tag|Tags', $n);
	}

	public static function representingColumn() {
		return 'tag';
	}

	public function rules() {
		return array(
			array('id, tag', 'required'),
			array('id, weight', 'length', 'max'=>11),
			array('tag', 'length', 'max'=>50),
			array('weight', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tag, weight', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tag' => Yii::t('app', 'Tag'),
			'weight' => Yii::t('app', 'Weight'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('tag', $this->tag, true);
		$criteria->compare('weight', $this->weight, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}