<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<?php echo $modelClass; ?>|<?php echo $this->pluralize($modelClass); ?>' => '',
  'Abuse archive' => '',
  'Abuses' => '',
  'Actions' => '',
  'Add network zone' => '',
  'Add torrent' => '',
  'Advanced Search' => '',
  'All' => '',
  'Assign roles' => '',
  'Attribute "{attribute}" should be string or integer or instance of MongoInt32 or MongoInt64 based on type parameter, instance of "{class}" is given.' => '',
  'Controller' => '',
  'Create' => '',
  'Create user' => '',
  'Delete' => '',
  'Fields with' => '',
  'Home' => '',
  'Index' => '',
  'Invalid key "{key}".' => '',
  'List' => '',
  'Logout' => '',
  'Manage' => '',
  'Manage network zones' => '',
  'Manage permission items' => '',
  'New torrents' => '',
  'No' => '',
  'Save' => '',
  'Search' => '',
  'The following items doesn\'t seem to belong to a controller.' => '',
  'Torrents list' => '',
  'Update' => '',
  'Upload torrent.' => '',
  'View' => '',
  'Yes' => '',
  'Your request is invalid.' => '',
  'are required' => '',
  'password' => '',
  '{$label}' => '',
);
