<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Auth item "{item}" does not exist. Please <a href="{link}" target="_blank">create</a> item first.' => '',
  'Auth item "{item}" in permission list does not exist. Create this item first.' => '',
  'Auth manager is not set in application.' => '',
  'Controller wasn\'t set.' => '',
  'Could not save torrent file.' => '',
  'Failed to validate meta data.' => '',
  'File {file} is not writable. Please make sure that file is writable under system user {user}.' => '',
  'Invalid id "{id}" or torrent is blocked.' => '',
  'Invalid id "{id}".' => '',
  'Invalid network mask {mask}. Must be bit or netmask (127.0.0.0/8 or 127.0.0.0/255.0.0.0).' => '',
  'Invalid type set. Expects to be integer with value 32 or 64, "{value}" is given' => '',
  'Item "{item}" is invalid.' => '',
  'Subnet {subnet} already exist in database and belongs to "{zone}" zone.' => '',
  'Supported languages are not set. Please configure application first.' => '',
  'Torrent was already uploaded early.' => '',
);
